### PR TITLE
add zhenge's profile

### PR DESCRIPTION
**Pull request by zhengezhao**

### CODE REVIEW

**Comment by seanastephens** [comment]
Great. Could you resize your image to be 200 x 261 pixels? This way it is the same size as the other images on the site. You can use the testing instructions in README.md to test that it looks right.

**Comment by zhengezhao** [comment]
Hi Sean,

I have done that , Could you recheck it  for me ? Thank you.

Regards,
Zhenge

**Comment by cscheid** [comment]
This looks good to me. I'm going to go ahead and merge it. You should see the changes take effect in a few minutes.

**Comment by cscheid** [comment]
This looks good to me. I'm going to go ahead and merge it. You should see the changes take effect in a few minutes.

**Pull request merged**
