### PR TITLE
Added Benafsh picture

### PR DESCRIPTION
**Pull request by husainb**

### CODE REVIEW

**Comment by cscheid** [comment]
HI Benafsh, can you resize the photo so that it's 200x267? That way it'll match the other images. Thanks!

**Comment by cscheid** [comment]
I think you needed to crop the original picture slightly, otherwise the aspect ratio gets a little out of whack, right? Sorry be a stickler here :)

**Comment by husainb** [comment]
Not a problem. Will crop the image and add it. Thanks

**Comment by cscheid** [comment]
Wow, did I really not merge this? Shame on me. Sorry about that!

**Pull request merged**
